# prometheus.yml example
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['host.docker.internal:9090']#'host.docker.internal:9090'
#    - targets: ['localhost:9080']
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9080']
        #'ecom_prometheus_local:9080','ecom_prometheus:9090','host.docker.internal:9090'] # Replace with your application's host and port
        #,'localhost:5000','host.docker.internal:5000'

  - job_name: 'eureka'
    eureka_sd_configs:
      - server: 'http://host.docker.internal:5000/eureka' # Replace with your Eureka server URL
    relabel_configs:
      - source_labels: [ __meta_eureka_app_instance_metadata_prometheus_path ]
        target_label: __metrics_path__
        regex: (.+)
        replacement: $1
      - source_labels: [ __meta_eureka_app_instance_metadata_prometheus_scrape ]
        action: keep
        regex: true

#  - job_name: 'eureka-server'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: [ 'host.docker.internal:9095']#,'eureka-server:8761' ]
#     - targets: [ 'localhost:5000']#,'eureka-server:8761' ]